@extends('layouts.admin')

@section('title', 'Backup Details - HealthLink Admin')
@section('header', 'Backup Details')

@section('actions')
    <div class="flex items-center space-x-2">
        <a href="{{ route('admin.backups.index') }}" class="inline-flex items-center rounded-md bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200">
            Back
        </a>
        @if($backup->is_verifiable)
            <form action="{{ route('admin.backups.verify', $backup) }}" method="POST">
                @csrf
                <button type="submit" class="inline-flex items-center rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700">
                    Verify Integrity
                </button>
            </form>
        @endif
        @if($backup->status === \App\Models\Backup::STATUS_COMPLETED)
            <a href="{{ route('admin.backups.download', $backup) }}" class="inline-flex items-center rounded-md bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-700">
                Download
            </a>
        @endif
    </div>
@endsection

@section('content')
    @if(! empty($capabilities['issues']))
        <div class="mb-6 rounded-lg border border-amber-300 bg-amber-50 p-4">
            <p class="text-sm font-semibold text-amber-900">Recovery Readiness Notes</p>
            <ul class="mt-2 space-y-1 text-sm text-amber-800">
                @foreach($capabilities['issues'] as $issue)
                    <li>{{ $issue }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="mb-6 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5">
        <div class="rounded-lg bg-white p-4 shadow">
            <dt class="text-sm font-medium text-gray-500">Status</dt>
            <dd class="mt-2">{!! $backup->status_badge !!}</dd>
        </div>
        <div class="rounded-lg bg-white p-4 shadow">
            <dt class="text-sm font-medium text-gray-500">Integrity</dt>
            <dd class="mt-2">{!! $backup->integrity_badge !!}</dd>
        </div>
        <div class="rounded-lg bg-white p-4 shadow">
            <dt class="text-sm font-medium text-gray-500">File Size</dt>
            <dd class="mt-2 text-lg font-semibold text-gray-900">{{ $backup->formatted_file_size }}</dd>
        </div>
        <div class="rounded-lg bg-white p-4 shadow">
            <dt class="text-sm font-medium text-gray-500">Restore Count</dt>
            <dd class="mt-2 text-lg font-semibold text-gray-900">{{ $backup->restore_count }}</dd>
        </div>
        <div class="rounded-lg bg-white p-4 shadow">
            <dt class="text-sm font-medium text-gray-500">Storage File</dt>
            <dd class="mt-2 text-lg font-semibold {{ $backup->has_stored_file ? 'text-emerald-700' : 'text-rose-700' }}">
                {{ $backup->has_stored_file ? 'Present' : 'Missing' }}
            </dd>
        </div>
    </div>

    <div class="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div class="xl:col-span-2 space-y-6">
            <div class="rounded-lg bg-white shadow">
                <div class="border-b border-gray-200 px-6 py-4">
                    <h3 class="text-lg font-medium text-gray-900">Backup Overview</h3>
                </div>
                <dl class="grid grid-cols-1 gap-4 p-6 md:grid-cols-2">
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Filename</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->filename }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Type</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->backup_type_label }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Generated By</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->generator?->name ?? 'Unknown' }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Created At</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->created_at?->format('Y-m-d H:i:s') }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Expires At</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->expires_at?->format('Y-m-d H:i:s') ?? 'Never' }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Storage Path</dt>
                        <dd class="mt-1 break-all text-sm text-gray-900">{{ $backup->absolute_path }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Last Verified</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->last_verified_at?->format('Y-m-d H:i:s') ?? 'Not checked yet' }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Checksum (SHA-256)</dt>
                        <dd class="mt-1 break-all text-sm text-gray-900">{{ $backup->checksum_sha256 ?? 'Not captured yet' }}</dd>
                    </div>
                    <div class="md:col-span-2">
                        <dt class="text-sm font-medium text-gray-500">Notes</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->notes ?: 'No notes provided.' }}</dd>
                    </div>
                </dl>
            </div>

            <div class="rounded-lg bg-white shadow">
                <div class="border-b border-gray-200 px-6 py-4">
                    <h3 class="text-lg font-medium text-gray-900">Recovery History</h3>
                </div>
                <dl class="grid grid-cols-1 gap-4 p-6 md:grid-cols-2">
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Last Restored At</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->last_restored_at?->format('Y-m-d H:i:s') ?? 'Not restored yet' }}</dd>
                    </div>
                    <div>
                        <dt class="text-sm font-medium text-gray-500">Last Restored By</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $restoredBy?->name ?? 'N/A' }}</dd>
                    </div>
                    <div class="md:col-span-2">
                        <dt class="text-sm font-medium text-gray-500">Last Restore Notes</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->metadataValue('last_restore_notes') ?: 'No restore notes recorded.' }}</dd>
                    </div>
                    <div class="md:col-span-2">
                        <dt class="text-sm font-medium text-gray-500">Last Restore Error</dt>
                        <dd class="mt-1 text-sm text-gray-900">{{ $backup->metadataValue('last_restore_error') ?: 'No restore errors recorded.' }}</dd>
                    </div>
                    <div class="md:col-span-2">
                        <dt class="text-sm font-medium text-gray-500">Metadata Snapshot</dt>
                        <dd class="mt-1 overflow-x-auto rounded-md bg-gray-50 p-4 text-xs text-gray-700">
                            <pre>{{ json_encode($backup->metadata ?? [], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>
                        </dd>
                    </div>
                </dl>
            </div>
        </div>

        <div class="space-y-6">
            <div class="rounded-lg border border-amber-300 bg-amber-50 p-5">
                <h3 class="text-lg font-medium text-amber-900">Restore Warning</h3>
                <p class="mt-2 text-sm text-amber-800">
                    Restoring a backup writes SQL directly into the active database. Use this only when you have confirmed the backup file, the target environment, and the expected downtime.
                </p>
            </div>

            <div class="rounded-lg bg-white shadow">
                <div class="border-b border-gray-200 px-6 py-4">
                    <h3 class="text-lg font-medium text-gray-900">Restore This Backup</h3>
                </div>
                <div class="p-6">
                    @if(! $backup->is_restorable)
                        <p class="text-sm text-gray-600">This backup cannot be restored because the file is unavailable or the backup did not complete successfully.</p>
                    @elseif(! $capabilities['restore_supported'])
                        <p class="text-sm text-gray-600">Restore tooling is not ready on this server yet. Review the readiness notes above first.</p>
                    @else
                        <div class="space-y-4">
                            <div class="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
                                This action executes SQL against the live database. Only continue when the restore window, source file, and recovery reason have been verified.
                            </div>
                            <x-destructive-confirm-modal
                                :action="route('admin.backups.restore', $backup)"
                                method="POST"
                                title="Restore Database Backup"
                                description="This will attempt to restore the selected SQL backup into the active HealthLink database."
                                trigger-label="Restore Backup"
                                trigger-class="inline-flex items-center rounded-md bg-rose-600 px-4 py-2 text-sm font-medium text-white hover:bg-rose-700"
                                confirmation-word="RESTORE"
                                submit-label="Run Restore"
                                reason-label="Restore reason"
                                reason-placeholder="State the incident, restore window, or recovery reason for this database restore."
                            />
                        </div>
                    @endif
                </div>
            </div>

            <div class="rounded-lg bg-white shadow">
                <div class="border-b border-gray-200 px-6 py-4">
                    <h3 class="text-lg font-medium text-gray-900">Quick Actions</h3>
                </div>
                <div class="space-y-3 p-6">
                    @if($backup->is_verifiable)
                        <form method="POST" action="{{ route('admin.backups.verify', $backup) }}">
                            @csrf
                            <button type="submit" class="w-full rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700">
                                Re-Verify Integrity
                            </button>
                        </form>
                    @endif

                    @if($backup->status === \App\Models\Backup::STATUS_COMPLETED)
                        <a href="{{ route('admin.backups.download', $backup) }}" class="block w-full rounded-md bg-emerald-600 px-4 py-2 text-center text-sm font-medium text-white hover:bg-emerald-700">
                            Download SQL File
                        </a>
                    @endif

                    <form method="POST" action="{{ route('admin.backups.destroy', $backup) }}" onsubmit="return confirm('Are you sure you want to delete this backup?')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="w-full rounded-md bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200">
                            Delete Backup
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
