@extends('layouts.portal')
@section('title', 'BNS Dashboard - HealthLink')
@section('header', 'BNS Dashboard')
@section('subheader', 'Nutrition-only monitoring: OPT+ measurements and barangay nutrition services.')
@section('actions')<a href="{{ route('bns.opt-cycles.index') }}" class="rounded-xl bg-tubigon px-4 py-2 text-sm text-white">Open OPT+</a>@endsection
@section('content')
    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 class="text-lg font-semibold">Latest OPT+ Cycle Coverage</h2>
        <p class="mt-2 text-sm text-slate-500">{{ $recentCampaigns->first()?->title ?? 'No OPT+ cycle yet' }}. Open a cycle to continue recording measurements.</p>
        <dl class="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4">@foreach(['Eligible Children' => $cycleSummary['eligible'], 'Measured' => $cycleSummary['measured'], 'Unmeasured' => $cycleSummary['unmeasured'], 'Coverage' => $cycleSummary['coverage'].'%'] as $label => $value)<div class="rounded-xl bg-slate-50 p-4"><dt class="text-sm text-slate-500">{{ $label }}</dt><dd class="mt-2 text-2xl font-semibold">{{ $value }}</dd></div>@endforeach</dl>
        <p class="mt-4 text-sm text-slate-500">{{ $activeCampaignCount }} cycle(s) in progress.</p>
    </section>
    <div class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Feeding Programs' => [$activeFeedingProgramCount, 'bns.feeding-programs.index'], 'Maternal Tracking' => [$pregnantResidentCount + $lactatingResidentCount, 'bns.maternal.index'], 'Nutrition Reference Cases' => [$targetClientCount, 'bns.watchlist.index'], 'Open Assessment Flags' => [$openAssessmentFlagCount, 'bns.watchlist.index']] as $label => $item)<a href="{{ route($item[1]) }}" class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-semibold text-tubigon">{{ $item[0] }}</p></a>@endforeach</div>
    <p class="mt-3 text-xs text-slate-500">Maternal total counts pregnancy/lactation statuses; one person may have both. Nutrition classifications are internal references, not official workbook results.</p>
    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-lg font-semibold">Recent OPT+ Cycles</h2><div class="mt-4 divide-y divide-slate-200">@forelse($recentCampaigns as $cycle)<a href="{{ route('bns.opt-cycles.show', $cycle) }}" class="flex flex-wrap justify-between gap-3 py-4"><span class="font-semibold text-tubigon">{{ $cycle->title }}</span><span class="text-sm text-slate-600">{{ $cycle->measured_count }} / {{ $cycle->entries_count }} measured - {{ $cycle->status === 'completed' ? 'Completed' : 'In Progress' }}</span></a>@empty<p class="py-4 text-slate-500">Create your first OPT+ cycle to begin.</p>@endforelse</div></section>
    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-lg font-semibold">Open Assessment Flags</h2><p class="mt-1 text-sm text-slate-500">These require explicit review and resolution; recording an OPT measurement does not close them.</p><div class="mt-4 divide-y divide-slate-200">@forelse($openFlags as $flag)<div class="py-4"><p class="font-semibold">{{ $flag->resident?->formal_name ?? 'Historical resident' }}</p><p class="mt-1 text-sm text-slate-600">{{ $flag->flag_reason }}</p></div>@empty<p class="py-4 text-slate-500">No open assessment flags.</p>@endforelse</div><a href="{{ route('bns.watchlist.index') }}" class="mt-3 inline-block text-sm font-semibold text-tubigon">Review Nutrition References and Flags</a></section>
@endsection
