<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use App\Models\Purok;
use App\Models\Barangay;
use App\Models\AuditLog;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'assigned_barangay_id',
        'assigned_purok_id',
        'is_active',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'is_active' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    /**
     * The available user roles.
     */
    public const ROLES = [
        'admin' => 'System Administrator',
        'mho' => 'Municipal Health Officer',
        'phn' => 'Public Health Nurse',
        'secretary' => 'Barangay Secretary',
        'bns' => 'Barangay Nutrition Scholar',
        'bhw' => 'Barangay Health Worker',
    ];

    /**
     * Role scope definitions for quick checks.
     */
    public const GLOBAL_ROLES = ['admin', 'mho', 'phn'];
    public const BARANGAY_ROLES = ['secretary', 'bns'];
    public const PUROK_ROLES = ['bhw'];

    // =============================================
    // RELATIONSHIPS
    // =============================================

    /**
     * Get the barangay assigned to this user.
     */
    public function assignedBarangay()
    {
        return $this->belongsTo(Barangay::class, 'assigned_barangay_id');
    }

    /**
     * Get the purok assigned to this user.
     */
    public function assignedPurok()
    {
        return $this->belongsTo(Purok::class, 'assigned_purok_id');
    }

    /**
     * Get all audit logs created by this user.
     */
    public function auditLogs()
    {
        return $this->hasMany(AuditLog::class);
    }

    /**
     * Get all sync logs created by this user.
     */
    public function syncLogs()
    {
        return $this->hasMany(SyncLog::class);
    }

    /**
     * Get all backups generated by this user.
     */
    public function backups()
    {
        return $this->hasMany(Backup::class, 'generated_by');
    }

    /**
     * Get all records archived by this user.
     */
    public function archivedRecords()
    {
        return $this->hasMany(ArchivedRecord::class, 'archived_by');
    }

    /**
     * Get all records purged by this user.
     */
    public function purgedRecords()
    {
        return $this->hasMany(ArchivedRecord::class, 'purged_by');
    }

    // =============================================
    // SCOPES
    // =============================================

    /**
     * Scope a query to only include active users.
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope a query to only include inactive users.
     */
    public function scopeInactive($query)
    {
        return $query->where('is_active', false);
    }

    /**
     * Scope a query to only include users with a specific role.
     */
    public function scopeWithRole($query, $role)
    {
        return $query->where('role', $role);
    }

    /**
     * Scope a query to only include users with global scope (admin, mho, phn).
     */
    public function scopeGlobal($query)
    {
        return $query->whereIn('role', self::GLOBAL_ROLES);
    }

    /**
     * Scope a query to only include users with barangay scope (secretary, bns).
     */
    public function scopeBarangayScope($query)
    {
        return $query->whereIn('role', self::BARANGAY_ROLES);
    }

    /**
     * Scope a query to only include users with purok scope (bhw).
     */
    public function scopePurokScope($query)
    {
        return $query->whereIn('role', self::PUROK_ROLES);
    }

    /**
     * Scope a query to only include users assigned to a specific barangay.
     */
    public function scopeAssignedToBarangay($query, $barangayId)
    {
        return $query->where('assigned_barangay_id', $barangayId);
    }

    /**
     * Scope a query to only include users assigned to a specific purok.
     */
    public function scopeAssignedToPurok($query, $purokId)
    {
        return $query->where('assigned_purok_id', $purokId);
    }

    // =============================================
    // ACCESSORS & MUTATORS
    // =============================================

    /**
     * Get the user's role label.
     */
    public function getRoleLabelAttribute(): string
    {
        return self::ROLES[$this->role] ?? $this->role;
    }

    /**
     * Get the user's full assignment description.
     */
    public function getAssignmentLabelAttribute(): string
    {
        if (in_array($this->role, self::GLOBAL_ROLES)) {
            return 'Municipality-wide';
        }

        if (in_array($this->role, self::BARANGAY_ROLES)) {
            return $this->assignedBarangay ? $this->assignedBarangay->name : 'No Barangay Assigned';
        }

        if (in_array($this->role, self::PUROK_ROLES)) {
            if ($this->assignedBarangay && $this->assignedPurok) {
                return $this->assignedBarangay->name . ' - Purok ' . $this->assignedPurok->purok_number;
            }
            return 'No Assignment';
        }

        return 'Unknown';
    }

    /**
     * Get the user's scope level.
     */
    public function getScopeLevelAttribute(): string
    {
        if (in_array($this->role, self::GLOBAL_ROLES)) {
            return 'global';
        }

        if (in_array($this->role, self::BARANGAY_ROLES)) {
            return 'barangay';
        }

        if (in_array($this->role, self::PUROK_ROLES)) {
            return 'purok';
        }

        return 'unknown';
    }

    // =============================================
    // HELPER METHODS
    // =============================================

    /**
     * Check if the user has a global role.
     */
    public function isGlobal(): bool
    {
        return in_array($this->role, self::GLOBAL_ROLES);
    }

    /**
     * Check if the user has a barangay-scoped role.
     */
    public function isBarangayScoped(): bool
    {
        return in_array($this->role, self::BARANGAY_ROLES);
    }

    /**
     * Check if the user has a purok-scoped role.
     */
    public function isPurokScoped(): bool
    {
        return in_array($this->role, self::PUROK_ROLES);
    }

    /**
     * Check if the user is a specific role.
     */
    public function isRole($role): bool
    {
        return $this->role === $role;
    }

    /**
     * Check if the user is active.
     */
    public function isActive(): bool
    {
        return $this->is_active && !$this->trashed();
    }

    /**
     * Determine if the user can access a specific barangay's data.
     */
    public function canAccessBarangay($barangayId): bool
    {
        if ($this->isGlobal()) {
            return true;
        }

        return $this->assigned_barangay_id === $barangayId;
    }

    /**
     * Determine if the user can access a specific purok's data.
     */
    public function canAccessPurok($purokId): bool
    {
        if ($this->isGlobal()) {
            return true;
        }

        if ($this->isBarangayScoped()) {
            // Check if the purok belongs to the user's assigned barangay
            $purok = Purok::where('id', $purokId)->first();
            return $purok && $this->assigned_barangay_id === $purok->barangay_id;
        }

        return $this->assigned_purok_id === $purokId;
    }
}