<?php

namespace App\Models;

use App\Notifications\ResetPasswordNotification;
use App\Notifications\VerifyEmailNotification;
use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use App\Models\Purok;
use App\Models\Barangay;
use App\Models\AuditLog;

class User extends Authenticatable implements MustVerifyEmailContract
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'first_name',
        'middle_name',
        'last_name',
        'suffix',
        'email',
        'password',
        'role',
        'approval_status',
        'registered_via',
        'requested_role',
        'assigned_barangay_id',
        'assigned_purok_id',
        'requested_barangay_id',
        'requested_purok_id',
        'approval_notes',
        'email_verified_at',
        'approved_at',
        'approved_by',
        'rejected_at',
        'rejected_by',
        'is_active',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'is_active' => 'boolean',
        'approved_at' => 'datetime',
        'rejected_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    public const APPROVAL_PENDING = 'pending';
    public const APPROVAL_APPROVED = 'approved';
    public const APPROVAL_REJECTED = 'rejected';

    /**
     * The available user roles.
     */
    public const ROLES = [
        'admin' => 'System Administrator',
        'mho' => 'Municipal Health Officer',
        'phn' => 'Public Health Nurse',
        'secretary' => 'Barangay Secretary',
        'bns' => 'Barangay Nutrition Scholar',
        'bhw' => 'Barangay Health Worker',
    ];

    /**
     * Role scope definitions for quick checks.
     */
    public const GLOBAL_ROLES = ['admin', 'mho', 'phn'];
    public const BARANGAY_ROLES = ['secretary', 'bns'];
    public const PUROK_ROLES = ['bhw'];
    public const SECRETARY_APPROVAL_ROLES = ['bhw', 'bns'];
    public const MUNICIPAL_APPROVAL_ROLES = ['admin', 'secretary', 'phn', 'mho'];

    protected static function booted(): void
    {
        static::saving(function (self $user): void {
            $user->syncNameColumns();
        });
    }

    /**
     * Send the HealthLink-branded email verification message.
     */
    public function sendEmailVerificationNotification(): void
    {
        $this->notify(new VerifyEmailNotification);
    }

    /**
     * Send the HealthLink-branded password reset message.
     */
    public function sendPasswordResetNotification($token): void
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    // =============================================
    // RELATIONSHIPS
    // =============================================

    /**
     * Get the barangay assigned to this user.
     */
    public function assignedBarangay()
    {
        return $this->belongsTo(Barangay::class, 'assigned_barangay_id');
    }

    /**
     * Get the purok assigned to this user.
     */
    public function assignedPurok()
    {
        return $this->belongsTo(Purok::class, 'assigned_purok_id');
    }

    /**
     * Get the requested barangay for a self-registration.
     */
    public function requestedBarangay()
    {
        return $this->belongsTo(Barangay::class, 'requested_barangay_id');
    }

    /**
     * Get the requested purok for a self-registration.
     */
    public function requestedPurok()
    {
        return $this->belongsTo(Purok::class, 'requested_purok_id');
    }

    /**
     * Get all audit logs created by this user.
     */
    public function auditLogs()
    {
        return $this->hasMany(AuditLog::class);
    }

    /**
     * Get all sync logs created by this user.
     */
    public function syncLogs()
    {
        return $this->hasMany(SyncLog::class);
    }

    /**
     * Get all backups generated by this user.
     */
    public function backups()
    {
        return $this->hasMany(Backup::class, 'generated_by');
    }

    /**
     * Get all records archived by this user.
     */
    public function archivedRecords()
    {
        return $this->hasMany(ArchivedRecord::class, 'archived_by');
    }

    /**
     * Get all records purged by this user.
     */
    public function purgedRecords()
    {
        return $this->hasMany(ArchivedRecord::class, 'purged_by');
    }

    /**
     * Get all users approved by this user.
     */
    public function approvedUsers()
    {
        return $this->hasMany(self::class, 'approved_by');
    }

    /**
     * Get all users rejected by this user.
     */
    public function rejectedUsers()
    {
        return $this->hasMany(self::class, 'rejected_by');
    }

    /**
     * Get all field visits recorded by this user.
     */
    public function fieldVisits()
    {
        return $this->hasMany(FieldVisit::class, 'recorded_by_user_id');
    }

    public function philpenRiskAssessments()
    {
        return $this->hasMany(PhilpenRiskAssessment::class, 'recorded_by_user_id');
    }

    /**
     * Get all barangay certificates issued by this user.
     */
    public function issuedCertificates()
    {
        return $this->hasMany(BarangayCertificate::class, 'issued_by_user_id');
    }

    public function submittedHouseholdDrafts()
    {
        return $this->hasMany(HouseholdDraft::class, 'submitted_by_user_id');
    }

    public function reviewedHouseholdDrafts()
    {
        return $this->hasMany(HouseholdDraft::class, 'reviewed_by_user_id');
    }

    public function submittedProfileUpdateRequests()
    {
        return $this->hasMany(ProfileUpdateRequest::class, 'submitted_by_user_id');
    }

    public function reviewedProfileUpdateRequests()
    {
        return $this->hasMany(ProfileUpdateRequest::class, 'reviewed_by_user_id');
    }

    public function recordedTriages()
    {
        return $this->hasMany(TriageRecord::class, 'recorded_by_user_id');
    }

    public function consumedTriages()
    {
        return $this->hasMany(TriageRecord::class, 'consumed_by_user_id');
    }

    public function clinicalEncounters()
    {
        return $this->hasMany(ClinicalEncounter::class, 'attended_by_user_id');
    }

    public function mhoClinicalReviews()
    {
        return $this->hasMany(MhoClinicalReview::class, 'reviewed_by_user_id');
    }

    public function createdNutritionCampaignPeriods()
    {
        return $this->hasMany(NutritionCampaignPeriod::class, 'created_by_user_id');
    }

    public function optMeasurements()
    {
        return $this->hasMany(OptMeasurement::class, 'measured_by_user_id');
    }

    public function childNutritionFlagsRaised()
    {
        return $this->hasMany(ChildNutritionAssessmentFlag::class, 'flagged_by_user_id');
    }

    public function childNutritionFlagsClosed()
    {
        return $this->hasMany(ChildNutritionAssessmentFlag::class, 'closed_by_user_id');
    }

    public function createdCommunityCampaigns()
    {
        return $this->hasMany(CommunityCampaign::class, 'created_by_user_id');
    }

    public function communityCampaignAssignments()
    {
        return $this->hasMany(CommunityCampaignAssignment::class, 'assigned_bhw_user_id');
    }

    // =============================================
    // SCOPES
    // =============================================

    /**
     * Scope a query to only include active users.
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope a query to only include inactive users.
     */
    public function scopeInactive($query)
    {
        return $query->where('is_active', false);
    }

    /**
     * Scope a query to only include users with a specific role.
     */
    public function scopeWithRole($query, $role)
    {
        return $query->where('role', $role);
    }

    /**
     * Scope a query to only include users with global scope (admin, mho, phn).
     */
    public function scopeGlobal($query)
    {
        return $query->whereIn('role', self::GLOBAL_ROLES);
    }

    /**
     * Scope a query to only include users with barangay scope (secretary, bns).
     */
    public function scopeBarangayScope($query)
    {
        return $query->whereIn('role', self::BARANGAY_ROLES);
    }

    /**
     * Scope a query to only include users with purok scope (bhw).
     */
    public function scopePurokScope($query)
    {
        return $query->whereIn('role', self::PUROK_ROLES);
    }

    /**
     * Scope a query to only include users assigned to a specific barangay.
     */
    public function scopeAssignedToBarangay($query, $barangayId)
    {
        return $query->where('assigned_barangay_id', $barangayId);
    }

    /**
     * Scope a query to only include users assigned to a specific purok.
     */
    public function scopeAssignedToPurok($query, $purokId)
    {
        return $query->where('assigned_purok_id', $purokId);
    }

    /**
     * Scope a query to only include pending registrations.
     */
    public function scopePendingApproval($query)
    {
        return $query->where('approval_status', self::APPROVAL_PENDING);
    }

    // =============================================
    // ACCESSORS & MUTATORS
    // =============================================

    public static function buildDisplayName(
        ?string $firstName,
        ?string $middleName,
        ?string $lastName,
        ?string $suffix = null
    ): string {
        $parts = array_filter([
            static::normalizeNamePart($firstName),
            static::normalizeNamePart($middleName),
            static::normalizeNamePart($lastName),
        ]);

        $name = trim(implode(' ', $parts));
        $suffix = static::normalizeNamePart($suffix);

        if ($suffix !== null && $suffix !== '') {
            $name = trim($name.' '.$suffix);
        }

        return preg_replace('/\s+/', ' ', $name) ?? $name;
    }

    public static function buildFormalName(
        ?string $firstName,
        ?string $middleName,
        ?string $lastName,
        ?string $suffix = null
    ): string {
        $firstName = static::normalizeNamePart($firstName);
        $middleName = static::normalizeNamePart($middleName);
        $lastName = static::normalizeNamePart($lastName);
        $suffix = static::normalizeNamePart($suffix);

        if ($lastName === null || $lastName === '') {
            return static::buildDisplayName($firstName, $middleName, null, $suffix);
        }

        $name = trim($lastName.', '.trim(implode(' ', array_filter([$firstName, $middleName]))));

        if ($suffix !== null && $suffix !== '') {
            $name = trim($name.' '.$suffix);
        }

        return preg_replace('/\s+/', ' ', $name) ?? $name;
    }

    public static function parseLegacyName(?string $name): array
    {
        $normalized = preg_replace('/\s+/', ' ', trim((string) $name)) ?? '';

        if ($normalized === '') {
            return [
                'first_name' => null,
                'middle_name' => null,
                'last_name' => null,
                'suffix' => null,
            ];
        }

        $tokens = preg_split('/\s+/', $normalized) ?: [];
        $suffix = null;

        if (count($tokens) > 1) {
            $candidateSuffix = strtoupper((string) end($tokens));

            if (preg_match('/^(JR\.?|SR\.?|I{1,4}|V|VI{0,3}|IX|X)$/', $candidateSuffix)) {
                $suffix = array_pop($tokens);
            }
        }

        if (count($tokens) === 1) {
            return [
                'first_name' => $tokens[0],
                'middle_name' => null,
                'last_name' => null,
                'suffix' => $suffix,
            ];
        }

        $firstName = array_shift($tokens);
        $lastName = array_pop($tokens);
        $middleName = count($tokens) > 0 ? implode(' ', $tokens) : null;

        return [
            'first_name' => $firstName,
            'middle_name' => $middleName,
            'last_name' => $lastName,
            'suffix' => $suffix,
        ];
    }

    public function getDisplayNameAttribute(): string
    {
        if ($this->first_name || $this->last_name) {
            return static::buildDisplayName(
                $this->first_name,
                $this->middle_name,
                $this->last_name,
                $this->suffix
            );
        }

        return trim((string) $this->name);
    }

    public function getFormalNameAttribute(): string
    {
        if ($this->first_name || $this->last_name) {
            return static::buildFormalName(
                $this->first_name,
                $this->middle_name,
                $this->last_name,
                $this->suffix
            );
        }

        return trim((string) $this->name);
    }

    public function getResolvedFirstNameAttribute(): ?string
    {
        return $this->first_name ?: $this->legacyNameParts()['first_name'];
    }

    public function getResolvedMiddleNameAttribute(): ?string
    {
        return $this->middle_name ?: $this->legacyNameParts()['middle_name'];
    }

    public function getResolvedLastNameAttribute(): ?string
    {
        return $this->last_name ?: $this->legacyNameParts()['last_name'];
    }

    public function getResolvedSuffixAttribute(): ?string
    {
        return $this->suffix ?: $this->legacyNameParts()['suffix'];
    }

    /**
     * Get the user's role label.
     */
    public function getRoleLabelAttribute(): string
    {
        return self::ROLES[$this->role] ?? ((string) $this->role !== '' ? (string) $this->role : 'User Account');
    }

    /**
     * Get the user's full assignment description.
     */
    public function getAssignmentLabelAttribute(): string
    {
        if (in_array($this->role, self::GLOBAL_ROLES)) {
            return 'Municipality-wide';
        }

        if (in_array($this->role, self::BARANGAY_ROLES)) {
            return $this->assignedBarangay ? $this->assignedBarangay->name : 'No Barangay Assigned';
        }

        if (in_array($this->role, self::PUROK_ROLES)) {
            if ($this->assignedBarangay && $this->assignedPurok) {
                return $this->assignedBarangay->name . ' - Purok ' . $this->assignedPurok->purok_number;
            }
            return 'No Assignment';
        }

        return 'Unknown';
    }

    /**
     * Get the user's scope level.
     */
    public function getScopeLevelAttribute(): string
    {
        if (in_array($this->role, self::GLOBAL_ROLES)) {
            return 'global';
        }

        if (in_array($this->role, self::BARANGAY_ROLES)) {
            return 'barangay';
        }

        if (in_array($this->role, self::PUROK_ROLES)) {
            return 'purok';
        }

        return 'unknown';
    }

    /**
     * Get the user's approval status label.
     */
    public function getApprovalStatusLabelAttribute(): string
    {
        return match ($this->approval_status) {
            self::APPROVAL_PENDING => 'Pending Approval',
            self::APPROVAL_APPROVED => 'Approved',
            self::APPROVAL_REJECTED => 'Rejected',
            default => 'Unknown',
        };
    }

    /**
     * Get the approval queue owner for this account request.
     */
    public function getApprovalQueueAttribute(): string
    {
        $targetRole = $this->requested_role ?: $this->role;

        if (in_array($targetRole, self::SECRETARY_APPROVAL_ROLES, true)) {
            return 'secretary';
        }

        return 'municipal';
    }

    /**
     * Get the approval queue label for dashboards and listings.
     */
    public function getApprovalQueueLabelAttribute(): string
    {
        return $this->approval_queue === 'secretary'
            ? 'Secretary Approval Queue'
            : 'Municipal Admin Queue';
    }

    /**
     * Get the registration source label.
     */
    public function getRegisteredViaLabelAttribute(): string
    {
        return match ((string) $this->registered_via) {
            'admin' => 'Admin',
            'self' => 'Self Registration',
            'bns' => 'BNS',
            'seed' => 'Seed Data',
            'secretary' => 'Secretary',
            default => str((string) $this->registered_via)
                ->replace(['_', '-'], ' ')
                ->title()
                ->toString(),
        };
    }

    /**
     * Get the email verification status label.
     */
    public function getEmailVerificationStatusLabelAttribute(): string
    {
        return $this->hasVerifiedEmail() ? 'Verified' : 'Unverified';
    }

    // =============================================
    // HELPER METHODS
    // =============================================

    /**
     * Check if the user has a global role.
     */
    public function isGlobal(): bool
    {
        return in_array($this->role, self::GLOBAL_ROLES);
    }

    /**
     * Check if the user has a barangay-scoped role.
     */
    public function isBarangayScoped(): bool
    {
        return in_array($this->role, self::BARANGAY_ROLES);
    }

    /**
     * Check if the user has a purok-scoped role.
     */
    public function isPurokScoped(): bool
    {
        return in_array($this->role, self::PUROK_ROLES);
    }

    /**
     * Check if the user is a specific role.
     */
    public function isRole($role): bool
    {
        return $this->role === $role;
    }

    /**
     * Check if the user is active.
     */
    public function isActive(): bool
    {
        return $this->is_active && !$this->trashed();
    }

    /**
     * Check whether the account is approved.
     */
    public function isApproved(): bool
    {
        return $this->approval_status === self::APPROVAL_APPROVED;
    }

    /**
     * Determine if the user can access a specific barangay's data.
     */
    public function canAccessBarangay($barangayId): bool
    {
        if ($this->isGlobal()) {
            return true;
        }

        return $this->assigned_barangay_id === $barangayId;
    }

    /**
     * Determine if the user can access a specific purok's data.
     */
    public function canAccessPurok($purokId): bool
    {
        if ($this->isGlobal()) {
            return true;
        }

        if ($this->isBarangayScoped()) {
            // Check if the purok belongs to the user's assigned barangay
            $purok = Purok::where('id', $purokId)->first();
            return $purok && $this->assigned_barangay_id === $purok->barangay_id;
        }

        return $this->assigned_purok_id === $purokId;
    }

    private static function normalizeNamePart(?string $value): ?string
    {
        if ($value === null) {
            return null;
        }

        $normalized = preg_replace('/\s+/', ' ', trim($value)) ?? '';

        return $normalized !== '' ? $normalized : null;
    }

    private function syncNameColumns(): void
    {
        $this->first_name = static::normalizeNamePart($this->first_name);
        $this->middle_name = static::normalizeNamePart($this->middle_name);
        $this->last_name = static::normalizeNamePart($this->last_name);
        $this->suffix = static::normalizeNamePart($this->suffix);

        if ($this->first_name || $this->last_name) {
            $this->name = static::buildDisplayName(
                $this->first_name,
                $this->middle_name,
                $this->last_name,
                $this->suffix
            );
        } else {
            $this->name = trim((string) $this->name);
        }
    }

    private function legacyNameParts(): array
    {
        return static::parseLegacyName($this->name);
    }
}
